### ISSUE TITLE
Cannot create container for service spark: No command specified

### ISSUE THREAD

**Issue by sgaseretto** [takaomag/docker.image.spark#1]
I'm trying to use your image and mount it with docker-compose, but when I run `docker-compose up` it gives me the following error:
```
ERROR: for spark  Cannot create container for service spark: No command specified
ERROR: Encountered errors while bringing up the project.
```
Any idea of what else do I need to specify in order to use it?

**Comment by takaomag** [comment]
@sgaseretto 

Sorry for late reply.
The error message means that a service is missing a command, since my dockerfile has no `ENTRYPOINT` and `CMD`.
Although I don't know docker-compose well, I guess you have to defile `command:` in the docker-compose.yml.

**Comment by takaomag** [comment]
closed.
